# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "swaggie"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Huie"]
  s.date = "2013-07-23"
  s.description = "Identify SQL bottlenecks"
  s.email = "david@nationbuilder.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/swaggie.rb",
    "lib/swaggie/database.rb",
    "lib/swaggie/dataset.rb",
    "lib/swaggie/filters/abstract_filter.rb",
    "lib/swaggie/filters/duration_filter.rb",
    "lib/swaggie/models/sql_statement.rb",
    "lib/swaggie/orm_adapters/abstract_orm_adapter.rb",
    "lib/swaggie/orm_adapters/activerecord_adapter.rb",
    "lib/swaggie/sampler.rb",
    "spec/dataset_spec.rb",
    "spec/filters/abstract_filter_spec.rb",
    "spec/filters/duration_filter_spec.rb",
    "spec/models/sql_statement_spec.rb",
    "spec/orm_adapters/abstract_orm_adapter_spec.rb",
    "spec/orm_adapters/activerecord_orm_adapter_spec.rb",
    "spec/sampler_spec.rb",
    "spec/spec_helper.rb",
    "spec/swaggie_spec.rb",
    "specification.txt",
    "swaggie.gemspec"
  ]
  s.homepage = "http://github.com/3dna/swaggie"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Identify SQL bottlenecks"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sequel>, [">= 0"])
      s.add_runtime_dependency(%q<sqlite3>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.2"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<database_cleaner>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<pry-nav>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<sequel>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<activesupport>, ["~> 3.2"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<database_cleaner>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<pry-nav>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<sequel>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<activesupport>, ["~> 3.2"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<database_cleaner>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<pry-nav>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

